### ISSUE TITLE
cl : Command line error D8021: invalid numeric argument '/Werror' [...\BigNumber\build\src\BigNumber.vcxproj]

### ISSUE THREAD

**Issue by JL2014** [ocineh/BigNumber#2]
Hi @ocineh,

Could you change this line (in your [CMakeLists.txt](https://github.com/ocineh/BigNumber/blob/main/CMakeLists.txt)) :
```
set(OPTIONS -Wall -Wextra -Werror -pedantic -Wshadow -Wsign-conversion)
```
by :
```
if(CMAKE_COMPILER_IS_GNUCXX)
    message(STATUS "GCC detected, adding compile flags")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Werror -pedantic -Wshadow -Wsign-conversion")
endif(CMAKE_COMPILER_IS_GNUCXX)
```
as mentionned on :
https://stackoverflow.com/questions/2274006/cmake-invalid-numeric-argument-wextra

Greetings, JL.

**Comment by ocineh** [comment]
Hi, I made the modification as indicated

**Comment by JL2014** [comment]
Thank you.
